services:
  - type: web
    name: inventario-api
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
